-- liquibase formatted sql

-- changeset Asus:1739646090104-1
CREATE TABLE hotel_amenities
(
    hotel_id  BIGINT NOT NULL,
    amenities VARCHAR(255)
);

-- changeset Asus:1739646090104-2
CREATE TABLE tb_hotels
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    description  VARCHAR(255),
    brand        VARCHAR(255),
    house_number VARCHAR(255),
    street       VARCHAR(255),
    city         VARCHAR(255),
    county       VARCHAR(255),
    post_code    VARCHAR(255),
    phone        VARCHAR(255),
    email        VARCHAR(255),
    check_in     time,
    check_out    time,
    CONSTRAINT pk_tb_hotels PRIMARY KEY (id)
);

-- changeset Asus:1739646090104-3
ALTER TABLE hotel_amenities
    ADD CONSTRAINT fk_hotel_amenities_on_hotel FOREIGN KEY (hotel_id) REFERENCES tb_hotels (id);

